finished basic combat task
MadalinaKopacz/gaming-project pull request #7
Opened 2022-11-04 18:26 UTC by Rodioo

2022-11-04 19:19 UTC, matei-dorian requested changes

2022-11-04 19:19 UTC, matei-dorian commented on Game Dev/Assets/Scripts/Enemy/AIPatrol.cs
> +    public List<Transform> points;
Datele membre ar trebui sa fie private daca nu exista un motiv bun pentru care sa fie publice

2022-11-04 19:19 UTC, matei-dorian commented on Game Dev/Assets/Scripts/Enemy/AIPatrol.cs
> +        transform.SetParent(root.transform);
new line dupa linia asta, sa fie mai usor de urmarit codul

2022-11-04 19:19 UTC, matei-dorian commented on Game Dev/Assets/Scripts/Enemy/AIPatrol.cs
> +        waypoints.transform.position = root.transform.position;
si aici new line

2022-11-04 19:19 UTC, matei-dorian commented on Game Dev/Assets/Scripts/Enemy/AIPatrol.cs
> +        points = new List<Transform>();
nit: points = new List<Transform>{p1.transform, p2.transform};

2022-11-04 19:19 UTC, matei-dorian commented on Game Dev/Assets/Scripts/Enemy/AIPatrol.cs
> +            transform.localScale = new Vector2(-4, 4);
ar trebui sa avem o variabila scale care sa reprezinte dimensiunea inamicului si sa o putem modifica direct din unity

2022-11-04 19:19 UTC, matei-dorian commented on Game Dev/Assets/Scripts/Enemy/AIPatrol.cs
> +            transform.localScale = new Vector2(-4, 4);
transform.localScale = new Vector2(-1, 1) * scale;

2022-11-04 19:19 UTC, matei-dorian commented on Game Dev/Assets/Scripts/Enemy/Rat.cs
> +    // Start is called before the first frame update
nu cred ca este necesar sa definesti functiile Start si Update in cazul asta

2022-11-04 19:19 UTC, matei-dorian commented on Game Dev/Assets/Scripts/Player/Shooting/Bullet.cs
> +    private Vector3 mousePos;
de ce mousePos e Vector3 si nu Vector2?

2022-11-04 19:49 UTC, Rodioo commented on Game Dev/Assets/Scripts/Player/Shooting/Bullet.cs
> +    private Vector3 mousePos;
pentru ca transform.position e Vector3

2022-11-05 16:47 UTC, matei-dorian approved these changes

2022-11-05 18:12 UTC, merged